name: Copy Repository

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Copy and Commit to Another Repository
      run: |
        mkdir -p temp_repo
        cd temp_repo
        git clone git@github.com:markfinn0/teste_mobile.git
        cd teste_mobile
        cp -R "${GITHUB_WORKSPACE}/." .
        git add .
        git commit -m "Copy repository changes"
        GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa" git push
