on:
  push:
    branches: [main, teste]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Change to Repository Directory
        run: cd $GITHUB_WORKSPACE  # Change to the root directory of the repository
        
      - name: Deploy files to repo
        # You may pin to the exact commit or the version.
        # uses: NeoHsu/deploy-files-to-repo@ba8c9fe91b89d4bd62ffab751eacf19c5b80e11b
        uses: NeoHsu/deploy-files-to-repo@v1.1.0
        with:
          # Deploy file or folder from this repo
          source_dir: 'origin_imgs'
          # Target GitHub personal access token
          target_personal_access_token: ${{ secrets.API_TOKEN_GITHUB }}
          # Target GitHub owner
          target_owner: 'markfinn0'
          # Target GitHub repository
          target_repo: 'teste_mobile'
          # Target GitHub repository branch
          target_dir: 'origin_imgs'
          commit_msg: 'teste'
     

        
          
