name: CI

on:
  push:
    branches: [main, teste]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Change to Repository Directory
        run: cd $GITHUB_WORKSPACE  # Change to the root directory of the repository

      - name: Push to Another Repository
        run: |
          rsync -av --delete-excluded origin_imgs/ markfinn0@teste_mobile:origin_imgs/
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
