on:
  push:
    branches: [main, teste]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Change to Repository Directory
        run: cd $GITHUB_WORKSPACE  # Change to the root directory of the repository

      - name: Push to Another Repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'origin_imgs/'
          destination-username: 'markfinn0'
          destination-repository: 'teste_mobile.github.io'
          destination-directory: 'origin_imgs'
          commit-email: 'marquinhossouzarodrigueslive@gmail.com'
