name: CI

on:
  push:
    branches: [main, teste]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy origin_imgs to Another Repository
        run: |
          mkdir -p temp_repo
          cd temp_repo
          git clone "https://github.com/markfinn0/teste_mobile.git"
          cd teste_mobile
          rm -rf origin_imgs/*  # Limpa o conteúdo existente da pasta origin_imgs
          cp -R "${GITHUB_WORKSPACE}/origin_imgs"/* origin_imgs/
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add origin_imgs/*
          git commit -m "Update origin_imgs"
          git push origin main
