name: CI

on:
  push:
    branches: [main, teste]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Change to Repository Directory
        run: cd $GITHUB_WORKSPACE  # Change to the root directory of the repository

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create and Push to New Branch
        run: |
          BRANCH_NAME="update-origin-imgs-$(date +'%Y%m%d%H%M%S')"
          git checkout -b $BRANCH_NAME
          mkdir -p temp_repo
          cd temp_repo
          git clone "git@github.com:markfinn0/teste_mobile.git"
          cd teste_mobile
          rm -rf origin_imgs/*  # Limpa o conteúdo existente da pasta origin_imgs
          cp -R "${GITHUB_WORKSPACE}/origin_imgs/." origin_imgs  # Copia apenas os arquivos da pasta origin_imgs
          git add origin_imgs/*
          git commit -m "Update origin_imgs"
          git push origin $BRANCH_NAME
        env:
          SSH_DEPLOY_KEY: ${{ secrets.GH_TOKEN }}
