name: Copy Repository

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout teste_mobile
      uses: actions/checkout@v2
      with:
        repository: markfinn0/teste_mobile

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        echo -n $ACCESS_TOKEN > ~/.github_token
        git config --global credential.helper "store --file=$HOME/.github_token"

    - name: Copy Changes from Design_CARDENA to teste_mobile
      run: |
        cd ..
        rm -rf teste_mobile/*  # Remove todos os arquivos existentes no teste_mobile
        cp -R Design_CARDENA/. teste_mobile
        cd teste_mobile
        git add .
        git commit -m "Copy repository changes from Design_CARDENA"
        git push

