name: CI

on:
  push:
    branches: [main, teste]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Output
        run: sh ./build.sh

      - name: Push to Another Repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: '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'  # Use GITHUB_TOKEN instead of API_TOKEN_GITHUB
        with:
          source-directory: 'https://github.com/markfinn0/Design_CARDENA.git'
          destination-github-username: 'markfinn0'  # Troque para o seu nome de usuário do GitHub
          destination-repository-name: 'https://github.com/markfinn0/teste_mobile.git'
          user-email: 'marquinhossouzarodrigueslive@gmail.com'  # Troque para o seu endereço de e-mail do GitHub
          target-branch: main
