name: Copy All Files

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Move to Project Directory
      run: cd Design_CARDENA

    - name: Clone MOBILE_TCC Repository
      run: |
        git clone https://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@github.com/markfinn0/teste_mobile.git ../teste_mobile

    - name: Configure Git for MOBILE_TCC Repository
      run: |
        cd ../teste_mobile
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Create and Checkout New Branch
      run: git checkout -b copy_branch

    - name: Copy New Files to MOBILE_TCC
      run: |
        find ../Design_CARDENA -type f -exec cp --parents {} . \;

    - name: Commit and Push to MOBILE_TCC
      run: |
        git add .
        git commit -m "Copy new files from Design_CARDENA"
        git push origin copy_branch
