name: Copy Repository

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositories
      run: |
        git config --global user.name "markfinn0"
        git config --global credential.username "markfinn0"
        git config --global user.email "marquinhossouzarodrigueslive@gmail.com"
        git config --global url.https://${{ secrets.API_TOKEN_GITHUB }}@github.com/.insteadOf https://github.com/
        git config --global credential.useHttpPath true
        git clone https://github.com/markfinn0/teste_mobile.git
        git clone https://github.com/markfinn0/Design_CARDENA.git
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Show content of teste_mobile before copying
      run: |
        cp -r Design_CARDENA/origin_imgs teste_mobile/
        cd teste_mobile/
        git checkout teste
        git add .
        git commit -m "Copy repository changes from Design_CARDENA"
        git push --set-upstream origin teste
