name: Copy Repository

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositories
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git clone https://$ACCESS_TOKEN@github.com/markfinn0/teste_mobile.git
        git clone https://$ACCESS_TOKEN@github.com/markfinn0/Design_CARDENA.git
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Show content of teste_mobile before copying
      run: |
        cp -r Design_CARDENA/origin_imgs teste_mobile/
        cd teste_mobile/
        git checkout teste
        git add .
        git commit -m "Copy repository changes from Design_CARDENA"
        git push --set-upstream origin teste

    - name: Git Push
      run: |
        git push --set-upstream origin teste
