name: CI

on:
  push:
    branches: [main, teste]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Output
        run: sh ./build.sh

      - name: Push to Another Repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN instead of API_TOKEN_GITHUB
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: '.'  # Ponto indica o diretório atual
          destination-github-username: 'markfinn0'
          destination-repository-name: 'teste_mobile'
          user-email: 'marquinhossouzarodrigueslive@gmail.com'
          target-branch: main
