name: CI

on:
  push:
    branches: [main, teste]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push generated webpage to another repository
        uses: nkoppel/push-files-to-another-repository@1.33.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'origin_imgs/'
          destination-username: 'markfinn0'
          destination-repository: 'teste_mobile.github.io'
          destination-directory: 'origin_imgs'
          commit-email: 'marquinhossouzarodrigueslive@gmail.com'
