name: Copy Repository

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositories
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        git clone git@github.com:markfinn0/teste_mobile.git
        git clone git@github.com:markfinn0/Design_CARDENA.git
        
    - name: Show content of teste_mobile before copying
      run: |
        cp -r Design_CARDENA/origin_imgs teste_mobile/
        cd teste_mobile/
        git add .
        git commit -m "Copy repository changes from Design_CARDENA"
        git push --set-upstream origin main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_DEPLOY_KEY }}

      
      

  
