name: CI

on:
  push:
    branches: [main, teste]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Copy files to another repository
        uses: nkoppel/push-files-to-another-repository@v1.1.2
        with:
          source-files: "origin_imgs/*"
          destination-username: "markfinn0"
          destination-repository: "teste_mobile"
          destination-branch: "main"
          destination-directory: "origin_imgs"
          commit-email: "marquinhossouzarodrigueslive@gmail.com"
          commit-message: "Update from ORIGIN_COMMIT"
