name: Copy OpenAPI File

on:
  push:
    branches:
      - main  # Ajuste para a branch principal do reposit贸rio Design_CARDENA
    paths:
      - 'Design_CARDENA/notehub/api/openapi.yaml'

jobs:
  copy_openapi_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Design_CARDENA Repository
      uses: actions/checkout@v2
      with:
        repository: markfinn0/Design_CARDENA  # Ajuste para o seu reposit贸rio Design_CARDENA

    - name: Checkout teste_mobile Repository
      uses: actions/checkout@v2
      with:
        repository: markfinn0/teste_mobile  # Ajuste para o seu reposit贸rio teste_mobile

    - name: Copy OpenAPI file
      run: |
        cp Design_CARDENA/notehub/api/openapi.yaml teste_mobile/

    - name: Configure Git for teste_mobile Repository
      run: |
        cd teste_mobile
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Commit and Push to teste_mobile
      run: |
        git add .
        git commit -m "Copy OpenAPI file from Design_CARDENA"
        git push origin HEAD:refs/heads/main  # Ajuste para a branch principal do reposit贸rio teste_mobile
