name: Copy Repository

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositories
      run: |
        git config --global user.name "markfinn0"
        git config --global user.email "marquinhossouzarodrigueslive@gmail.com"
        echo -n $ACCESS_TOKEN > ~/.github_token
        git config --global credential.helper "store --file=$HOME/.github_token"
        mkdir -p ~/.ssh
        echo "$ACCESS_TOKEN" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        git clone https://github.com/markfinn0/teste_mobile.git
        git clone https://github.com/markfinn0/Design_CARDENA.git
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # Lembre-se de adicionar o ACCESS_TOKEN como um segredo no GitHub
    - name: Show content of teste_mobile before copying
      run: |
        cp -r Design_CARDENA/origin_imgs teste_mobile/
        cd teste_mobile/
        git checkout teste
        git add .
        git commit -m "Copy repository changes from Design_CARDENA"
        git push --set-upstream origin teste


      
      

  
