name: Copy Images and Info

on:
  pull_request:
    paths:
      - 'origin_imgs/**/*'
      - 'flutter/reuso/**/*'

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Clone MOBILE_TCC Repository
      run: |
        git clone https://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@github.com/markfinn0/teste_mobile.git ../teste_mobile

    - name: Configure Git for MOBILE_TCC Repository
      run: |
        cd ../teste_mobile
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Remove Existing origin_imgs in MOBILE_TCC
      run: |
        rm -rf origin_imgs

    - name: Copy Images and Info to MOBILE_TCC
      run: |
        cp -r ../Design_CARDENA/origin_imgs ../Design_CARDENA/flutter/reuso/* .

    - name: Commit and Push to MOBILE_TCC
      run: |
        git add .
        git commit -m "Copy images and info from Design_CARDENA"
        git push origin HEAD:refs/heads/main
