name: Copy Repository

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
        echo "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
        chmod 600 ~/.ssh/id_rsa
        chmod 700 ~/.ssh

    - name: Copy and Commit to Another Repository
      run: |
        mkdir -p temp_repo
        cd temp_repo
        git clone git@github.com:markfinn0/teste_mobile.git
        cd teste_mobile
        cp -R "${GITHUB_WORKSPACE}/." .
        git add .
        git commit -m "Copy repository changes"
        GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa" git push
