name: Copy Repository

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositories
      run: |
        mkdir -p temp_repo
        cd temp_repo
        git clone git@github.com:markfinn0/teste_mobile.git
        git clone git@github.com:markfinn0/Design_CARDENA.git
      # Não é necessário definir ACCESS_TOKEN ao usar SSH

    - name: Show content of teste_mobile before copying
      run: |
        cp -r Design_CARDENA/origin_imgs teste_mobile/
        cd teste_mobile/
        git checkout -b teste  # Cria e muda para a branch "teste"
        git add .
        git commit -m "Copy repository changes from Design_CARDENA"
        git push --set-upstream origin teste
