name: Copy Repository

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositories
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # Cria o diretório ~/.ssh se não existir
        mkdir -p ~/.ssh

        # Decodifica a chave privada da base64 e a salva no arquivo
        echo "${{ secrets.BASE64_ENCODED_KEY }}" | base64 --decode > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa

        # Adiciona a chave SSH ao agente SSH
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa

        # Adiciona a chave SSH ao known_hosts
        ssh-keyscan github.com >> ~/.ssh/known_hosts

        git clone git@github.com:markfinn0/teste_mobile.git
        git clone git@github.com:markfinn0/Design_CARDENA.git
      env:
        BASE64_ENCODED_KEY: ${{ secrets.ACCESS_TOKEN }}  # Lembre-se de adicionar a BASE64_ENCODED_KEY como um segredo no GitHub
    - name: Show content of teste_mobile before copying
      run: |
        cp -r Design_CARDENA/origin_imgs teste_mobile/
        cd teste_mobile/
        git checkout teste
        git add .
        git commit -m "Copy repository changes from Design_CARDENA"
        git push --set-upstream origin teste


      
      

  
