name: Copy Repository

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositories
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        echo -n $ACCESS_TOKEN > ~/.github_token
        git config --global credential.helper "store --file=$HOME/.github_token"
        git clone https://github.com/markfinn0/teste_mobile.git
        git clone https://github.com/markfinn0/Design_CARDENA.git
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # Lembre-se de adicionar o ACCESS_TOKEN como um segredo no GitHub

    - name: Copy Changes from Design_CARDENA to teste_mobile
      run: |
        rm -rf teste_mobile/*  # Remove todos os arquivos existentes no teste_mobile
        cp -R Design_CARDENA/. teste_mobile
        cd teste_mobile
        git add .
        git commit -m "Copy repository changes from Design_CARDENA"
        git push
