name: Copy Repository

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositorie
      run: |
        git config --global user.name "markfinn0"
        git config --global credential.username "markfinn0"
        git config --global user.email "marquinhossouzarodrigueslive@gmail.com"
        git config --global url.https://${{ secrets.API_TOKEN_GITHUB }}@github.com/.insteadOf https://github.com/
        git config --global credential.useHttpPath true
        git clone https://github.com/markfinn0/client_mobile.git
        git clone https://github.com/markfinn0/Design_CARDENA.git
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Copiar arquivos de volta para "Prod"
      run: |
        cd client_mobile/
        git checkout Prod
        cd ..
        cp -r ../Design_CARDENA/reuse_imgs client_mobile/assets/asset/
        cd client_mobile/
        git add .
        git commit -m "Copiar Design Atualizado | Workflow2"
        git push origin Prod

    - name: Copiar arquivos de volta para "Hom"
      run: |
        cd client_mobile/
        git checkout Hom
        cd ..
        cp -r Design_CARDENA/reuse_imgs client_mobile/assets/asset/
        cd client_mobile/
        git add .
        git commit -m "Copiar Design Atualizado | Workflow2"
        git push origin Hom

    - name: Copiar arquivos de volta para "Dev"
      run: |
        cd client_mobile/
        git checkout Dev
        cd ..
        cp -r Design_CARDENA/reuse_imgs client_mobile/assets/asset/
        cd client_mobile/
        git add .
        git commit -m "Copiar Design Atualizado | Workflow2"
        git push origin Dev
        
    
